### ISSUE TITLE
How could I change the code to make it stream audio?

### ISSUE THREAD

**Issue by DanDev46** [Jess-v/music-bot#2]
I would like the bot to stream the audio instead of download it as I am going to host the bot on heroku.

Help would be appreciated :)

**Comment by Jess-v** [comment]
@DanDev46 I believe I have a possible implementation for this - I'll rewrite and test it; if it works I'll update to stream instead of download.

**Comment by Jess-v** [comment]
Unfortunately it seems that this is a limitation without a great workaround - It's possible to stream short segments of audio but the URLs the bot uses to download/stream audio expire far too fast to stream an entire song. If you care to experiment with it further though, here's what you'd need to change in cogs/music.py:
```py
    async def play_song(self, guild: discord.Guild, song: Song):
        '''Downloads and starts playing a YouTube video's audio.'''

        voice = get(self.bot.voice_clients, guild=guild)
        queue = self.music_queues.get(guild)

        voice.play(discord.FFmpegPCMAudio(song["formats"][0]["url"]))
        queue.clear_skip_votes()
```

**Comment by DanDev46** [comment]
Ok. Thanks anyway!
